/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: slb.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "slb.pb-c.h"
void   slb__add_sa_req__init
                     (Slb__AddSaReq         *message)
{
  static const Slb__AddSaReq init_value = SLB__ADD_SA_REQ__INIT;
  *message = init_value;
}
size_t slb__add_sa_req__get_packed_size
                     (const Slb__AddSaReq *message)
{
  assert(message->base.descriptor == &slb__add_sa_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slb__add_sa_req__pack
                     (const Slb__AddSaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slb__add_sa_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slb__add_sa_req__pack_to_buffer
                     (const Slb__AddSaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slb__add_sa_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Slb__AddSaReq *
       slb__add_sa_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Slb__AddSaReq *)
     protobuf_c_message_unpack (&slb__add_sa_req__descriptor,
                                allocator, len, data);
}
void   slb__add_sa_req__free_unpacked
                     (Slb__AddSaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &slb__add_sa_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   slb__del_sa_req__init
                     (Slb__DelSaReq         *message)
{
  static const Slb__DelSaReq init_value = SLB__DEL_SA_REQ__INIT;
  *message = init_value;
}
size_t slb__del_sa_req__get_packed_size
                     (const Slb__DelSaReq *message)
{
  assert(message->base.descriptor == &slb__del_sa_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slb__del_sa_req__pack
                     (const Slb__DelSaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slb__del_sa_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slb__del_sa_req__pack_to_buffer
                     (const Slb__DelSaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slb__del_sa_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Slb__DelSaReq *
       slb__del_sa_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Slb__DelSaReq *)
     protobuf_c_message_unpack (&slb__del_sa_req__descriptor,
                                allocator, len, data);
}
void   slb__del_sa_req__free_unpacked
                     (Slb__DelSaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &slb__del_sa_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   slb__status_resp__init
                     (Slb__StatusResp         *message)
{
  static const Slb__StatusResp init_value = SLB__STATUS_RESP__INIT;
  *message = init_value;
}
size_t slb__status_resp__get_packed_size
                     (const Slb__StatusResp *message)
{
  assert(message->base.descriptor == &slb__status_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slb__status_resp__pack
                     (const Slb__StatusResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slb__status_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slb__status_resp__pack_to_buffer
                     (const Slb__StatusResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slb__status_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Slb__StatusResp *
       slb__status_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Slb__StatusResp *)
     protobuf_c_message_unpack (&slb__status_resp__descriptor,
                                allocator, len, data);
}
void   slb__status_resp__free_unpacked
                     (Slb__StatusResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &slb__status_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor slb__add_sa_req__field_descriptors[7] =
{
  {
    "host_src",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Slb__AddSaReq, host_src),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_src_mask",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Slb__AddSaReq, host_src_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_dst",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Slb__AddSaReq, host_dst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_dst_mask",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Slb__AddSaReq, host_dst_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tmpl_host_src",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Slb__AddSaReq, tmpl_host_src),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tmpl_host_dst",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Slb__AddSaReq, tmpl_host_dst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spi",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Slb__AddSaReq, spi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slb__add_sa_req__field_indices_by_name[] = {
  2,   /* field[2] = host_dst */
  3,   /* field[3] = host_dst_mask */
  0,   /* field[0] = host_src */
  1,   /* field[1] = host_src_mask */
  6,   /* field[6] = spi */
  5,   /* field[5] = tmpl_host_dst */
  4,   /* field[4] = tmpl_host_src */
};
static const ProtobufCIntRange slb__add_sa_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor slb__add_sa_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slb.AddSaReq",
  "AddSaReq",
  "Slb__AddSaReq",
  "slb",
  sizeof(Slb__AddSaReq),
  7,
  slb__add_sa_req__field_descriptors,
  slb__add_sa_req__field_indices_by_name,
  1,  slb__add_sa_req__number_ranges,
  (ProtobufCMessageInit) slb__add_sa_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slb__del_sa_req__field_descriptors[7] =
{
  {
    "host_src",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Slb__DelSaReq, host_src),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_src_mask",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Slb__DelSaReq, host_src_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_dst",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Slb__DelSaReq, host_dst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_dst_mask",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Slb__DelSaReq, host_dst_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tmpl_host_src",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Slb__DelSaReq, tmpl_host_src),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tmpl_host_dst",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Slb__DelSaReq, tmpl_host_dst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spi",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Slb__DelSaReq, spi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slb__del_sa_req__field_indices_by_name[] = {
  2,   /* field[2] = host_dst */
  3,   /* field[3] = host_dst_mask */
  0,   /* field[0] = host_src */
  1,   /* field[1] = host_src_mask */
  6,   /* field[6] = spi */
  5,   /* field[5] = tmpl_host_dst */
  4,   /* field[4] = tmpl_host_src */
};
static const ProtobufCIntRange slb__del_sa_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor slb__del_sa_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slb.DelSaReq",
  "DelSaReq",
  "Slb__DelSaReq",
  "slb",
  sizeof(Slb__DelSaReq),
  7,
  slb__del_sa_req__field_descriptors,
  slb__del_sa_req__field_indices_by_name,
  1,  slb__del_sa_req__number_ranges,
  (ProtobufCMessageInit) slb__del_sa_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slb__status_resp__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Slb__StatusResp, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slb__status_resp__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange slb__status_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor slb__status_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "slb.StatusResp",
  "StatusResp",
  "Slb__StatusResp",
  "slb",
  sizeof(Slb__StatusResp),
  1,
  slb__status_resp__field_descriptors,
  slb__status_resp__field_indices_by_name,
  1,  slb__status_resp__number_ranges,
  (ProtobufCMessageInit) slb__status_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
