// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64
// +build arm64be armbe mips mips64 mips64p32 ppc64 s390 s390x sparc sparc64

package slbrouter

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfMacaddr struct{ Mac [6]uint8 }

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	XdpIcmp          *ebpf.ProgramSpec `ebpf:"xdp_icmp"`
	XdpPassIg        *ebpf.ProgramSpec `ebpf:"xdp_pass_ig"`
	XdpPassTest      *ebpf.ProgramSpec `ebpf:"xdp_pass_test"`
	XdpRedirectInner *ebpf.ProgramSpec `ebpf:"xdp_redirect_inner"`
	XdpRedirectOuter *ebpf.ProgramSpec `ebpf:"xdp_redirect_outer"`
	XdpShowUdp       *ebpf.ProgramSpec `ebpf:"xdp_show_udp"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	MacArr      *ebpf.MapSpec `ebpf:"mac_arr"`
	RedirectMap *ebpf.MapSpec `ebpf:"redirect_map"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	MacArr      *ebpf.Map `ebpf:"mac_arr"`
	RedirectMap *ebpf.Map `ebpf:"redirect_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.MacArr,
		m.RedirectMap,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	XdpIcmp          *ebpf.Program `ebpf:"xdp_icmp"`
	XdpPassIg        *ebpf.Program `ebpf:"xdp_pass_ig"`
	XdpPassTest      *ebpf.Program `ebpf:"xdp_pass_test"`
	XdpRedirectInner *ebpf.Program `ebpf:"xdp_redirect_inner"`
	XdpRedirectOuter *ebpf.Program `ebpf:"xdp_redirect_outer"`
	XdpShowUdp       *ebpf.Program `ebpf:"xdp_show_udp"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.XdpIcmp,
		p.XdpPassIg,
		p.XdpPassTest,
		p.XdpRedirectInner,
		p.XdpRedirectOuter,
		p.XdpShowUdp,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
